project:
  type: website
  output-dir: docs
website:
  title: "shortCourse"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - regression.qmd

format:
  html:
    theme: mytheme.scss
    css: styles.css
    toc: true

editor: visual

