project:
  type: website
  output-dir: docs
website:
  title: "GAMLSS Short Course"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - regression.qmd
      - data.qmd
      - distributions.qmd
      - fitting.qmd
      - comparison.qmd
      - selection.qmd
      - interpretation.qmd
      
sidebar:
  contents: auto
      
format:
  html:
    theme: sky
    css: styles.css
    toc: true

editor: visual

